<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DateConverterForJson">
      <HintPath>..\..\DateConverterForJson\DateConverterForJson\bin\Release\net8.0\DateConverterForJson.dll</HintPath>
    </Reference>
    <Reference Include="FileNameHelper">
      <HintPath>..\..\FileNameHelper\FileNameHelper\bin\Release\net8.0\FileNameHelper.dll</HintPath>
    </Reference>
    <Reference Include="InputHelper">
      <HintPath>..\..\InputHelper\InputHelper\bin\Release\net8.0\InputHelper.dll</HintPath>
    </Reference>
    <Reference Include="PohybHelper">
      <HintPath>..\..\PohybHelper\PohybHelper\bin\Release\net8.0\PohybHelper.dll</HintPath>
    </Reference>
    <Reference Include="SelectHelper">
      <HintPath>..\..\SelectHelper\SelectHelper\bin\Release\net8.0\SelectHelper.dll</HintPath>
    </Reference>
    <Reference Include="TextHelper">
      <HintPath>..\..\TextHelper\TextHelper\bin\Release\net8.0\TextHelper.dll</HintPath>
    </Reference>
    <Reference Include="VekZviratHelper">
      <HintPath>..\..\VekZviratHelper\VekZviratHelper\bin\Release\net8.0\VekZviratHelper.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
